node {
  stage ('SCM Checkout') {
 def mvnHome = tool name: 'maven-3',type: 'maven'
  }
  stage ('Compile-Package') {
     def mvnHome = tool name: 'maven-3',type: 'maven'
         sh "${mvnHome}/bin/mvn package"
         }
   }
         
